### ISSUE TITLE
Jinja2 update to version 3 breaks nbsphinx

### ISSUE THREAD

**Issue by nikosavola** [spatialaudio/nbsphinx#563]
As Jinja2 version is not frozen to 2.11 in [setup.py](https://github.com/spatialaudio/nbsphinx/blob/master/setup.py#L18) nbsphinx uses the new version 3.0.0.

With Jinja2 3.0.0 I've been getting the following error for all notebooks
```
'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'
```
This does not happen if I freeze Jinja2 to 2.11.

**Comment by kif** [comment]
I confirm: `pip install  Jinja2==2.11` fixes the bug for me too 
https://readthedocs.org/projects/pyfai/builds/13742631/

**Comment by mgeier** [comment]
Thanks for reporting this!

It looks like the Jinja2 behavior changed, but I'm not entirely sure whether that was on purpose.

I'm not sure, but it's probably related to https://github.com/pallets/jinja/pull/1204

Jinja2 release notes: https://jinja.palletsprojects.com/en/3.0.x/changes/#version-3-0-0.

**Comment by mgeier** [comment]
Thanks for the fix in #564!
I've merged it and I've just made a new release https://pypi.org/project/nbsphinx/0.8.5/.

If anybody has an idea how to fix the root cause of the problem, please let me know!

**Comment by sammorley-short** [comment]
Just wanted to add that I am only seeing this bug for pip version 20.2 (well, specifically 20.2.4). Using `pip>=20.3.0` also solves the problem.

I'm not sure exactly what changed to cause this, but pip 20.3 made a load of changes to the resolver, so presumably it's one of the ones listed here: https://pip.pypa.io/en/stable/news/#v20-3

**Comment by astrojuanlu** [comment]
I fail to see how the pip version affects this 🤔

**Comment by sammorley-short** [comment]
Yeah, apologies, I wasn't particularly clear above. 

In my case the fix in 0.8.5 released yesterday still doesn't fix the problem if you are using pip < 20.3, since the release pegging was not obeyed. However, upgrading to pip >= 20.3 fixed the issue for me, presumably because of a change in the dependency resolution ordering between the two minor versions.

Not saying this because it's something that needs changing on the `nbsphinx` side, but just flagging this for anyone else who wasn't seeing 0.8.5 solve the problem. 🙂

**Comment by marscher** [comment]
I'm still observing the reported behavior with nbsphinx=0.8.5

**Comment by mgeier** [comment]
@marscher I think this has been fixed in https://github.com/conda-forge/nbsphinx-feedstock/pull/35, but probably there hasn't been a new release of the package?
You should probably create an issue over there.

**Comment by marscher** [comment]
@mgeier thanks a lot for the cref. I've checked this PR. As the build number has been increased, a new package containing the jinja version restriction has been built already. But strangely that does not circumvent the problem.

**Comment by marscher** [comment]
mhm, my own github actions pipeline works now, but not on RTD. The latter could be caused by a caching problem.

**Comment by edublancas** [comment]
I ran into a similar issue. I tracked down the error to this line: https://github.com/spatialaudio/nbsphinx/blob/7b65abc4c59c2a9db49fe23eb0c0bebf5c475490/src/nbsphinx.py#L282

The problem is a change in how jinja handles the "in" operator. e.g:

```python
from jinja2 Import Template
Template('{% if "something" in a.b %}{% endif %}').render(a=dict())
```

Previously, this would not raise any errors. But in 3.0.0 this happens:

```pytb
UndefinedError: 'dict object' has no attribute 'b'
```

`widgets` and `tags` are optional fields in a notebook's metadata.

One solution would be to provide a default value for them before checking its contents, just like nbconvert does:

```python
{% if mimetype in nb.metadata.get("widgets",{})%}
```

source: https://github.com/jupyter/nbconvert/blob/e49b9a8a220c9f9f87c23764ea7b48eac4707937/share/jupyter/nbconvert/templates/classic/base.html.j2#L258

**Comment by mgeier** [comment]
Thanks for the information @edublancas, would you like to make a PR to fix this?

**Comment by aiqc** [comment]
ReadTheDocs must have updated to Jinja2 v3 because my nbsphinx docs broke with the same "no tags attribute"

So I added a line for jinja2=2.11.2 to my ReadTheDocs-specific requirements.txt, and the build passes now.

**Comment by astrojuanlu** [comment]
@aiqc Just to clarify: Read the Docs installed the latest version of Jinja2 because you didn't have it pinned, as you later did here https://github.com/aiqc/AIQC/commit/2e94ead51fe

**Comment by mgeier** [comment]
I've created #573 to hopefully fix this issue. Can y'all please try it?

**Comment by astrojuanlu** [comment]
Worked for me! https://readthedocs.org/projects/poliastro/builds/13906083/ (Jinja2 3.0.1 and your nbsphinx branch installed)

**Comment by mgeier** [comment]
Thanks @astrojuanlu for testing!

I've just released version 0.8.6 with a fix for this issue.

**Comment by aiqc** [comment]
Tested with `nbsphinx==0.8.6` and `jinja2=3.0.1`. 

Also published to ReadTheDocs <https://aiqc.readthedocs.io/en/latest/notebooks/heterogeneous_features.html> successfully if you want to inspect anything.
