### ISSUE TITLE
embed bokeh plots

### ISSUE THREAD

**Issue by fdeheeger** [spatialaudio/nbsphinx#61]
I am wondering if there is a way to embed bokeh plot (and probably other rich js display) in the resulting sphinx doc ?
The first attempt led to the bokeh javascript loading step being deleted, the result of `output_notebook()` is being suppressed by nbsphinx.
That step could be solved by embedding the bokeh.js link in the html template, but then the bokeh "frame" gets an absolute position in the page (top left of the web page). 
Did you face that issue already ?

**Comment by mgeier** [comment]
No, I've never tried this. Can you please provide and example notebook? How does `nbconvert` handle this?

**Comment by fdeheeger** [comment]
Thanks for your feedback.

Here is an example of a notebook with a bokeh plot and some html conversion:
 - one using nbconvert 
 - one using nbsphinx (I created a small sphinx project to build it)
 - the same one with 2 manual additional lines to load bokeh.js and bokeh.css to be able to render the plot.

https://gist.github.com/fdeheeger/26cbac58ac94701f7b10f5536d7076ea

`nbconvert` is building a working html, where `nbsphinx` is getting rid of the part of the output area that contains the javascript loading.
The absolute position error I mentioned is solved, I just missed to add the css reference.

So the issue is just regarding the fact that nbsphinx does not keep the bokeh loading step, and so the plot is not rendered automagically.

**Comment by fdeheeger** [comment]
This stackoverflow solution helped me to find a workaround.
http://stackoverflow.com/questions/37096106/how-to-load-external-javascript-in-sphinx-doc

The idea is to override the layout by adding a `layout.html` file into the `_templates` folder. This is the content I used:

```
{% extends "!layout.html" %}

{%- block extrahead %}
    {{ super() }}
    <link href="_static/bokeh-0.12.0.min.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="_static/bokeh-0.12.0.js"></script>
{% endblock %}
```

**Comment by mgeier** [comment]
I've implemented this in #62. Can you please check if this works for you?

**Comment by fdeheeger** [comment]
Your fix fixes it !
Thanks, definitely useful to have the JavaScript output working magically (at least the bokeh one).

**Comment by mgeier** [comment]
There is still an issue with jQuery in the readthedocs theme: https://github.com/snide/sphinx_rtd_theme/issues/328.

**Comment by mgeier** [comment]
The bokeh example should work now, but jQuery is still not available when using the RTD theme.
